spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"   #Configurations from classpath in resources folder->config
          # search-locations: "file:///Users//shivamverma//config" #Configurations from file location
        git:
          uri: https://github.com/ShivamVerma380/eazybytes-config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"  

server:
  port: 8071

