spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"   #Configurations from classpath in resources folder->config
          # search-locations: "file:///Users//shivamverma//config" #Configurations from file location
        git:
          uri: https://github.com/eazybytes/eazybytes-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071

