server:
    port: 9010

spring:
    application:
        name: "message"
    cloud:
        function:
            definition: email|sms #Execute email, sms function together using pipe once we invoke /emailsms. 